# Generated by Django 3.2.4 on 2021-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.IntegerField()),
                ('output', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Фибоначи Input/Output',
            },
        ),
    ]
